export const site = {
  name: "Convert Studio",
  url: "https://convert-studio-web.onrender.com",
  description: "Free image and PDF conversion tools built for quick, private, and reliable file workflows.",
};

const sharedImageFaq = [
  ["Are my images uploaded?", "No. Browser image tools run locally on your device whenever possible."],
  ["Can I convert multiple files?", "Yes. You can add up to five files in the first-stage free workflow."],
  ["Will transparent images stay transparent?", "PNG and WebP can keep transparency. JPG does not support transparency, so transparent areas are filled with white."],
];

const sharedServerImageFaq = [
  ["Are HEIC or TIFF files uploaded?", "Yes. These formats need secure temporary server processing because browser support is inconsistent."],
  ["How long are files kept?", "Uploaded images and converted files are temporary and are scheduled for deletion after 30 minutes."],
  ["Why convert HEIC to JPG?", "JPG is accepted by more websites, forms, email systems, and older desktop apps than HEIC."],
];

const sharedPdfFaq = [
  ["How long are files kept?", "Server-processed files are temporary and are scheduled for deletion after 30 minutes."],
  ["Is PDF to Word always perfect?", "No. The first version is best effort. Complex layouts, scanned documents, and heavy tables may need manual cleanup."],
  ["What is the free file limit?", "The first-stage limit is 50 MB per file and up to five files per job."],
];

export const imageTools = [
  {
    slug: "heic-to-jpg",
    title: "HEIC to JPG Converter",
    category: "Image",
    mode: "server",
    input: "HEIC",
    output: "JPG",
    accept: ".heic,.heif,image/heic,image/heif",
    action: "heic-to-jpg",
    description: "Convert iPhone HEIC photos to widely compatible JPG files.",
    useCase: "Best when a website, form, email system, or Windows app will not accept photos saved by an iPhone.",
  },
  {
    slug: "png-to-jpg",
    title: "PNG to JPG Converter",
    category: "Image",
    mode: "browser",
    input: "PNG",
    output: "JPG",
    accept: "image/png",
    action: "image-convert",
    target: "image/jpeg",
    extension: "jpg",
    description: "Convert PNG images to JPG in your browser with a clean white background for transparent pixels.",
    useCase: "Best for sharing screenshots, product images, and web graphics where smaller JPG files are easier to upload.",
  },
  {
    slug: "jpg-to-png",
    title: "JPG to PNG Converter",
    category: "Image",
    mode: "browser",
    input: "JPG",
    output: "PNG",
    accept: "image/jpeg",
    action: "image-convert",
    target: "image/png",
    extension: "png",
    description: "Convert JPG photos to PNG locally in your browser.",
    useCase: "Useful when you need a lossless PNG container for editing, screenshots, or design workflows.",
  },
  {
    slug: "jpg-to-webp",
    title: "JPG to WebP Converter",
    category: "Image",
    mode: "browser",
    input: "JPG",
    output: "WebP",
    accept: "image/jpeg",
    action: "image-convert",
    target: "image/webp",
    extension: "webp",
    description: "Convert JPG files to modern WebP images for smaller website assets.",
    useCase: "Best for website owners who want lighter image files without a complicated design tool.",
  },
  {
    slug: "webp-to-png",
    title: "WebP to PNG Converter",
    category: "Image",
    mode: "browser",
    input: "WebP",
    output: "PNG",
    accept: "image/webp",
    action: "image-convert",
    target: "image/png",
    extension: "png",
    description: "Convert WebP images to PNG for apps and editors that do not support WebP.",
    useCase: "Helpful when a platform rejects WebP uploads or when you need a PNG for editing.",
  },
  {
    slug: "webp-to-jpg",
    title: "WebP to JPG Converter",
    category: "Image",
    mode: "browser",
    input: "WebP",
    output: "JPG",
    accept: "image/webp",
    action: "image-convert",
    target: "image/jpeg",
    extension: "jpg",
    description: "Convert WebP images to JPG for older apps, upload forms, and file previews.",
    useCase: "Useful when a downloaded web image is saved as WebP but the place you need to upload it only accepts JPG.",
  },
  {
    slug: "png-to-webp",
    title: "PNG to WebP Converter",
    category: "Image",
    mode: "browser",
    input: "PNG",
    output: "WebP",
    accept: "image/png",
    action: "image-convert",
    target: "image/webp",
    extension: "webp",
    description: "Convert PNG images to WebP for smaller web assets with transparency support.",
    useCase: "Good for website graphics, app screenshots, icons, and UI images that need smaller file sizes.",
  },
  {
    slug: "avif-to-jpg",
    title: "AVIF to JPG Converter",
    category: "Image",
    mode: "browser",
    input: "AVIF",
    output: "JPG",
    accept: "image/avif",
    action: "image-convert",
    target: "image/jpeg",
    extension: "jpg",
    description: "Convert AVIF images to JPG for broad compatibility.",
    useCase: "Helpful when modern AVIF images will not open in an older editor, CMS, or upload portal.",
  },
  {
    slug: "tiff-to-jpg",
    title: "TIFF to JPG Converter",
    category: "Image",
    mode: "server",
    input: "TIFF",
    output: "JPG",
    accept: ".tif,.tiff,image/tiff",
    action: "tiff-to-jpg",
    description: "Convert large TIFF images to practical JPG files.",
    useCase: "Useful for scanned documents, archive images, and print files that need to be shared or uploaded online.",
  },
  {
    slug: "compress-image",
    title: "Compress Image",
    category: "Image",
    mode: "browser",
    input: "Image",
    output: "Compressed image",
    accept: "image/png,image/jpeg,image/webp",
    action: "image-compress",
    target: "image/jpeg",
    extension: "jpg",
    description: "Reduce image file size in the browser using sensible JPG compression.",
    useCase: "Good for online forms, email attachments, real estate photos, and product listings.",
  },
  {
    slug: "resize-image",
    title: "Resize Image",
    category: "Image",
    mode: "browser",
    input: "Image",
    output: "Resized image",
    accept: "image/png,image/jpeg,image/webp",
    action: "image-resize",
    target: "image/jpeg",
    extension: "jpg",
    description: "Resize images to a practical web width while keeping the original aspect ratio.",
    useCase: "Use it when large phone photos need to fit upload limits or load faster on a website.",
  },
  {
    slug: "image-to-pdf",
    title: "Image to PDF Converter",
    category: "Image",
    mode: "browser",
    input: "Image",
    output: "PDF",
    accept: "image/png,image/jpeg,image/webp",
    action: "image-to-pdf",
    target: "application/pdf",
    extension: "pdf",
    description: "Create a simple PDF from one or more images directly in your browser.",
    useCase: "Perfect for receipts, IDs, homework photos, scanned pages, and document uploads.",
  },
];

export const pdfTools = [
  {
    slug: "word-to-pdf",
    title: "Word to PDF Converter",
    category: "PDF",
    mode: "server",
    input: "DOCX",
    output: "PDF",
    accept: ".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    action: "word-to-pdf",
    description: "Convert Word documents to PDF using a server-side office conversion engine.",
    useCase: "Use it for resumes, contracts, reports, and forms that need a shareable PDF copy.",
  },
  {
    slug: "pdf-to-word",
    title: "PDF to Word Converter",
    category: "PDF",
    mode: "server",
    input: "PDF",
    output: "DOCX",
    accept: "application/pdf",
    action: "pdf-to-word",
    description: "Turn simple PDFs into editable Word documents with best-effort layout recovery.",
    useCase: "Best for text-based PDFs. Scanned PDFs and complex layouts may need manual cleanup.",
  },
  {
    slug: "compress-pdf",
    title: "Compress PDF",
    category: "PDF",
    mode: "server",
    input: "PDF",
    output: "Smaller PDF",
    accept: "application/pdf",
    action: "compress-pdf",
    description: "Reduce PDF file size for uploads, emails, and storage.",
    useCase: "Helpful when forms, portals, or email systems reject a PDF because it is too large.",
  },
  {
    slug: "pdf-to-jpg",
    title: "PDF to JPG Converter",
    category: "PDF",
    mode: "server",
    input: "PDF",
    output: "JPG",
    accept: "application/pdf",
    action: "pdf-to-jpg",
    description: "Convert PDF pages into JPG images packaged for download.",
    useCase: "Useful for previews, thumbnails, image-only uploads, and quick sharing.",
  },
  {
    slug: "jpg-to-pdf",
    title: "JPG to PDF Converter",
    category: "PDF",
    mode: "browser",
    input: "JPG",
    output: "PDF",
    accept: "image/jpeg",
    action: "image-to-pdf",
    target: "application/pdf",
    extension: "pdf",
    description: "Combine JPG images into a PDF without uploading them.",
    useCase: "Great for receipts, IDs, signed forms, and photo-based documents.",
  },
  {
    slug: "merge-pdf",
    title: "Merge PDF",
    category: "PDF",
    mode: "server",
    input: "PDF",
    output: "Merged PDF",
    accept: "application/pdf",
    action: "merge-pdf",
    description: "Combine multiple PDF files into one document.",
    useCase: "Useful for applications, contracts, invoices, and report packs.",
  },
  {
    slug: "split-pdf",
    title: "Split PDF",
    category: "PDF",
    mode: "server",
    input: "PDF",
    output: "Split PDF",
    accept: "application/pdf",
    action: "split-pdf",
    description: "Extract pages from a PDF into a new file.",
    useCase: "Use it when you only need selected pages from a large PDF.",
  },
];

for (const tool of imageTools) {
  tool.faq = tool.mode === "server" ? sharedServerImageFaq : sharedImageFaq;
}

for (const tool of pdfTools) {
  tool.faq = sharedPdfFaq;
}

export const legalPages = [
  {
    slug: "privacy",
    title: "Privacy Policy",
    description: "How Convert Studio handles uploaded files, browser conversions, analytics, and advertising.",
    body: [
      "Browser-based tools process files locally on your device and do not upload them to our servers.",
      "Server-based PDF tools temporarily process files only to complete the requested conversion. Temporary files are scheduled for deletion after 30 minutes.",
      "We may use privacy-conscious analytics and advertising partners. Advertising placements must not interfere with uploads, conversion actions, or downloads.",
    ],
  },
  {
    slug: "terms",
    title: "Terms of Use",
    description: "The rules for using Convert Studio's free file conversion tools.",
    body: [
      "Use the service only for files you have the right to process.",
      "Do not upload malware, illegal content, or files intended to abuse the service.",
      "Conversions are provided as best-effort results. Always review important documents before sharing them.",
    ],
  },
  {
    slug: "contact",
    title: "Contact",
    description: "Contact Convert Studio for support, feedback, and policy questions.",
    body: [
      "For support, include the tool name, browser, file type, and the error message you saw.",
      "For privacy or advertising questions, include the page URL and a clear description of the issue.",
    ],
  },
  {
    slug: "about",
    title: "About Convert Studio",
    description: "Convert Studio is a practical file conversion site focused on images and PDFs.",
    body: [
      "Convert Studio focuses on the most common image and PDF tasks people need every day.",
      "The product favors fast browser-side conversion where possible and low-cost server processing only where it is necessary.",
    ],
  },
];
