export const site = {
  name: "FileForma",
  url: "https://fileforma.com",
  description: "Free image and PDF conversion tools from FileForma, built for quick, private, and reliable file workflows.",
  analyticsId: process.env.GA_MEASUREMENT_ID || "",
};

const sharedImageFaq = [
  ["Are my images uploaded?", "No. Browser image tools run locally on your device whenever possible."],
  ["Can I convert multiple files?", "Yes. You can add up to five files in the first-stage free workflow."],
  ["Will transparent images stay transparent?", "PNG and WebP can keep transparency. JPG does not support transparency, so transparent areas are filled with white."],
];

const sharedServerImageFaq = [
  ["Are HEIC or TIFF files uploaded?", "Yes. These formats need secure temporary server processing because browser support is inconsistent."],
  ["How long are files kept?", "Uploaded images and converted files are temporary and are scheduled for deletion after 30 minutes."],
  ["Why convert HEIC to JPG?", "JPG is accepted by more websites, forms, email systems, and older desktop apps than HEIC."],
];

const sharedPdfFaq = [
  ["How long are files kept?", "Server-processed files are temporary and are scheduled for deletion after 30 minutes."],
  ["Is PDF to Word always perfect?", "No. The first version is best effort. Complex layouts, scanned documents, and heavy tables may need manual cleanup."],
  ["What is the free file limit?", "The first-stage limit is 50 MB per file and up to five files per job."],
];

export const imageTools = [
  {
    slug: "heic-to-jpg",
    title: "HEIC to JPG Converter",
    category: "Image",
    icon: "camera",
    mode: "server",
    input: "HEIC",
    output: "JPG",
    accept: ".heic,.heif,image/heic,image/heif",
    action: "heic-to-jpg",
    description: "Convert iPhone HEIC photos to widely compatible JPG files.",
    useCase: "Best when a website, form, email system, or Windows app will not accept photos saved by an iPhone.",
  },
  {
    slug: "png-to-jpg",
    title: "PNG to JPG Converter",
    category: "Image",
    icon: "image-convert",
    mode: "browser",
    input: "PNG",
    output: "JPG",
    accept: "image/png",
    action: "image-convert",
    target: "image/jpeg",
    extension: "jpg",
    description: "Convert PNG images to JPG in your browser with a clean white background for transparent pixels.",
    useCase: "Best for sharing screenshots, product images, and web graphics where smaller JPG files are easier to upload.",
  },
  {
    slug: "jpg-to-png",
    title: "JPG to PNG Converter",
    category: "Image",
    icon: "image-convert",
    mode: "browser",
    input: "JPG",
    output: "PNG",
    accept: "image/jpeg",
    action: "image-convert",
    target: "image/png",
    extension: "png",
    description: "Convert JPG photos to PNG locally in your browser.",
    useCase: "Useful when you need a lossless PNG container for editing, screenshots, or design workflows.",
  },
  {
    slug: "jpg-to-webp",
    title: "JPG to WebP Converter",
    category: "Image",
    icon: "image-convert",
    mode: "browser",
    input: "JPG",
    output: "WebP",
    accept: "image/jpeg",
    action: "image-convert",
    target: "image/webp",
    extension: "webp",
    description: "Convert JPG files to modern WebP images for smaller website assets.",
    useCase: "Best for website owners who want lighter image files without a complicated design tool.",
  },
  {
    slug: "webp-to-png",
    title: "WebP to PNG Converter",
    category: "Image",
    icon: "image-convert",
    mode: "browser",
    input: "WebP",
    output: "PNG",
    accept: "image/webp",
    action: "image-convert",
    target: "image/png",
    extension: "png",
    description: "Convert WebP images to PNG for apps and editors that do not support WebP.",
    useCase: "Helpful when a platform rejects WebP uploads or when you need a PNG for editing.",
  },
  {
    slug: "webp-to-jpg",
    title: "WebP to JPG Converter",
    category: "Image",
    icon: "image-convert",
    mode: "browser",
    input: "WebP",
    output: "JPG",
    accept: "image/webp",
    action: "image-convert",
    target: "image/jpeg",
    extension: "jpg",
    description: "Convert WebP images to JPG for older apps, upload forms, and file previews.",
    useCase: "Useful when a downloaded web image is saved as WebP but the place you need to upload it only accepts JPG.",
  },
  {
    slug: "png-to-webp",
    title: "PNG to WebP Converter",
    category: "Image",
    icon: "image-convert",
    mode: "browser",
    input: "PNG",
    output: "WebP",
    accept: "image/png",
    action: "image-convert",
    target: "image/webp",
    extension: "webp",
    description: "Convert PNG images to WebP for smaller web assets with transparency support.",
    useCase: "Good for website graphics, app screenshots, icons, and UI images that need smaller file sizes.",
  },
  {
    slug: "avif-to-jpg",
    title: "AVIF to JPG Converter",
    category: "Image",
    icon: "image-convert",
    mode: "browser",
    input: "AVIF",
    output: "JPG",
    accept: "image/avif",
    action: "image-convert",
    target: "image/jpeg",
    extension: "jpg",
    description: "Convert AVIF images to JPG for broad compatibility.",
    useCase: "Helpful when modern AVIF images will not open in an older editor, CMS, or upload portal.",
  },
  {
    slug: "tiff-to-jpg",
    title: "TIFF to JPG Converter",
    category: "Image",
    icon: "image-stack",
    mode: "server",
    input: "TIFF",
    output: "JPG",
    accept: ".tif,.tiff,image/tiff",
    action: "tiff-to-jpg",
    description: "Convert large TIFF images to practical JPG files.",
    useCase: "Useful for scanned documents, archive images, and print files that need to be shared or uploaded online.",
  },
  {
    slug: "compress-image",
    title: "Compress Image",
    category: "Image",
    icon: "compress",
    mode: "browser",
    input: "Image",
    output: "Compressed image",
    accept: "image/png,image/jpeg,image/webp",
    action: "image-compress",
    target: "image/jpeg",
    extension: "jpg",
    description: "Reduce image file size in the browser using sensible JPG compression.",
    useCase: "Good for online forms, email attachments, real estate photos, and product listings.",
  },
  {
    slug: "resize-image",
    title: "Resize Image",
    category: "Image",
    icon: "resize",
    mode: "browser",
    input: "Image",
    output: "Resized image",
    accept: "image/png,image/jpeg,image/webp",
    action: "image-resize",
    target: "image/jpeg",
    extension: "jpg",
    description: "Resize images to a practical web width while keeping the original aspect ratio.",
    useCase: "Use it when large phone photos need to fit upload limits or load faster on a website.",
  },
  {
    slug: "image-to-pdf",
    title: "Image to PDF Converter",
    category: "Image",
    icon: "image-pdf",
    mode: "browser",
    input: "Image",
    output: "PDF",
    accept: "image/png,image/jpeg,image/webp",
    action: "image-to-pdf",
    target: "application/pdf",
    extension: "pdf",
    description: "Create a simple PDF from one or more images directly in your browser.",
    useCase: "Perfect for receipts, IDs, homework photos, scanned pages, and document uploads.",
  },
];

export const pdfTools = [
  {
    slug: "merge-pdf",
    title: "Merge PDF",
    category: "PDF",
    group: "Organize PDF",
    icon: "merge",
    mode: "server",
    input: "PDF",
    output: "Merged PDF",
    accept: "application/pdf",
    action: "merge-pdf",
    description: "Combine multiple PDF files into one document in the order you choose.",
    useCase: "Useful for applications, contracts, invoices, and report packs.",
  },
  {
    slug: "split-pdf",
    title: "Split PDF",
    category: "PDF",
    group: "Organize PDF",
    icon: "split",
    mode: "server",
    input: "PDF",
    output: "Split PDF",
    accept: "application/pdf",
    action: "split-pdf",
    option: "pages",
    description: "Extract selected pages from a PDF into a new file.",
    useCase: "Use it when you only need selected pages from a large PDF.",
  },
  {
    slug: "remove-pdf-pages",
    title: "Remove PDF Pages",
    category: "PDF",
    group: "Organize PDF",
    icon: "remove",
    mode: "server",
    input: "PDF",
    output: "PDF without selected pages",
    accept: "application/pdf",
    action: "remove-pdf-pages",
    option: "pages",
    description: "Delete unwanted pages from a PDF and download a clean copy.",
    useCase: "Helpful for removing blank pages, old forms, cover sheets, or pages that should not be shared.",
  },
  {
    slug: "extract-pdf-pages",
    title: "Extract PDF Pages",
    category: "PDF",
    group: "Organize PDF",
    icon: "extract",
    mode: "server",
    input: "PDF",
    output: "Extracted PDF",
    accept: "application/pdf",
    action: "extract-pdf-pages",
    option: "pages",
    description: "Save specific PDF pages as a separate document.",
    useCase: "Best when a long PDF contains a few pages you need to send, upload, or archive separately.",
  },
  {
    slug: "organize-pdf",
    title: "Organize PDF",
    category: "PDF",
    group: "Organize PDF",
    icon: "organize",
    mode: "server",
    input: "PDF",
    output: "Reordered PDF",
    accept: "application/pdf",
    action: "organize-pdf",
    option: "order",
    description: "Reorder PDF pages by typing the page order you want.",
    useCase: "Use it to rearrange scanned pages, reorder forms, or build a cleaner document before sharing.",
  },
  {
    slug: "compress-pdf",
    title: "Compress PDF",
    category: "PDF",
    group: "Optimize PDF",
    icon: "compress",
    mode: "server",
    input: "PDF",
    output: "Smaller PDF",
    accept: "application/pdf",
    action: "compress-pdf",
    description: "Reduce PDF file size for uploads, emails, and storage.",
    useCase: "Helpful when forms, portals, or email systems reject a PDF because it is too large.",
  },
  {
    slug: "repair-pdf",
    title: "Repair PDF",
    category: "PDF",
    group: "Optimize PDF",
    icon: "repair",
    mode: "server",
    input: "PDF",
    output: "Repaired PDF",
    accept: "application/pdf",
    action: "repair-pdf",
    description: "Rewrite a PDF structure to fix many common file issues.",
    useCase: "Best for PDFs that open slowly, have minor structure issues, or fail in some upload portals.",
  },
  {
    slug: "jpg-to-pdf",
    title: "JPG to PDF Converter",
    category: "PDF",
    group: "Convert to PDF",
    icon: "image-pdf",
    mode: "browser",
    input: "JPG",
    output: "PDF",
    accept: "image/jpeg",
    action: "image-to-pdf",
    target: "application/pdf",
    extension: "pdf",
    description: "Combine JPG images into a PDF without uploading them.",
    useCase: "Great for receipts, IDs, signed forms, and photo-based documents.",
  },
  {
    slug: "word-to-pdf",
    title: "Word to PDF Converter",
    category: "PDF",
    group: "Convert to PDF",
    icon: "word",
    mode: "server",
    input: "DOCX",
    output: "PDF",
    accept: ".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    action: "word-to-pdf",
    description: "Convert Word documents to PDF using a server-side office conversion engine.",
    useCase: "Use it for resumes, contracts, reports, and forms that need a shareable PDF copy.",
  },
  {
    slug: "powerpoint-to-pdf",
    title: "PowerPoint to PDF",
    category: "PDF",
    group: "Convert to PDF",
    icon: "slides",
    mode: "server",
    input: "PPTX",
    output: "PDF",
    accept: ".ppt,.pptx,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation",
    action: "powerpoint-to-pdf",
    description: "Convert PowerPoint presentations into shareable PDF files.",
    useCase: "Good for slides, pitch decks, training files, and presentations that need a stable PDF copy.",
  },
  {
    slug: "excel-to-pdf",
    title: "Excel to PDF",
    category: "PDF",
    group: "Convert to PDF",
    icon: "sheet",
    mode: "server",
    input: "XLSX",
    output: "PDF",
    accept: ".xls,.xlsx,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    action: "excel-to-pdf",
    description: "Convert Excel spreadsheets into PDF documents.",
    useCase: "Useful for tables, invoices, schedules, reports, and spreadsheet exports that need a PDF.",
  },
  {
    slug: "pdf-to-jpg",
    title: "PDF to JPG Converter",
    category: "PDF",
    group: "Convert from PDF",
    icon: "pdf-image",
    mode: "server",
    input: "PDF",
    output: "JPG",
    accept: "application/pdf",
    action: "pdf-to-jpg",
    description: "Convert PDF pages into JPG images packaged for download.",
    useCase: "Useful for previews, thumbnails, image-only uploads, and quick sharing.",
  },
  {
    slug: "pdf-to-word",
    title: "PDF to Word Converter",
    category: "PDF",
    group: "Convert from PDF",
    icon: "doc",
    mode: "server",
    input: "PDF",
    output: "DOCX",
    accept: "application/pdf",
    action: "pdf-to-word",
    description: "Turn simple PDFs into editable Word documents with best-effort layout recovery.",
    useCase: "Best for text-based PDFs. Scanned PDFs and complex layouts may need manual cleanup.",
  },
  {
    slug: "edit-pdf",
    title: "Edit PDF",
    category: "PDF",
    group: "Edit PDF",
    icon: "doc",
    mode: "server",
    input: "PDF",
    output: "Edited PDF",
    accept: "application/pdf",
    action: "edit-pdf",
    option: "text",
    description: "Add text to a selected PDF page and download an edited copy.",
    useCase: "Useful for adding a short note, label, reference number, or correction to an existing PDF without opening a desktop editor.",
  },
  {
    slug: "rotate-pdf",
    title: "Rotate PDF",
    category: "PDF",
    group: "Edit PDF",
    icon: "rotate",
    mode: "server",
    input: "PDF",
    output: "Rotated PDF",
    accept: "application/pdf",
    action: "rotate-pdf",
    option: "rotation",
    description: "Rotate all pages in a PDF clockwise by 90, 180, or 270 degrees.",
    useCase: "Helpful for scans, sideways pages, and documents saved in the wrong orientation.",
  },
  {
    slug: "add-page-numbers",
    title: "Add Page Numbers",
    category: "PDF",
    group: "Edit PDF",
    icon: "number",
    mode: "server",
    input: "PDF",
    output: "Numbered PDF",
    accept: "application/pdf",
    action: "add-page-numbers",
    description: "Add simple page numbers to the bottom of every PDF page.",
    useCase: "Useful for reports, contracts, applications, and document packs that need clear page references.",
  },
  {
    slug: "add-watermark",
    title: "Add Watermark",
    category: "PDF",
    group: "Edit PDF",
    icon: "watermark",
    mode: "server",
    input: "PDF",
    output: "Watermarked PDF",
    accept: "application/pdf",
    action: "add-watermark",
    option: "text",
    description: "Stamp text across PDF pages as a simple watermark.",
    useCase: "Use it for draft labels, internal documents, sample files, or ownership marks.",
  },
  {
    slug: "crop-pdf",
    title: "Crop PDF",
    category: "PDF",
    group: "Edit PDF",
    icon: "crop",
    mode: "server",
    input: "PDF",
    output: "Cropped PDF",
    accept: "application/pdf",
    action: "crop-pdf",
    option: "margin",
    description: "Crop equal margins from all sides of a PDF.",
    useCase: "Helpful when scanned PDFs have wide borders or extra white space around the content.",
  },
  {
    slug: "redact-pdf",
    title: "Redact PDF",
    category: "PDF",
    group: "Edit PDF",
    icon: "remove",
    mode: "server",
    input: "PDF",
    output: "Redacted PDF",
    accept: "application/pdf",
    action: "redact-pdf",
    option: "text",
    description: "Search for sensitive words or phrases and permanently cover matching text in a PDF.",
    useCase: "Helpful when you need to hide names, account numbers, emails, phone numbers, or other sensitive text before sharing a document.",
  },
  {
    slug: "sign-pdf",
    title: "Sign PDF",
    category: "PDF",
    group: "Edit PDF",
    icon: "watermark",
    mode: "server",
    input: "PDF",
    output: "Signed PDF",
    accept: "application/pdf",
    action: "sign-pdf",
    option: "text",
    description: "Place a typed signature on a PDF page.",
    useCase: "Useful for adding a simple approval mark or typed signature to internal forms, acknowledgements, and low-risk documents.",
  },
  {
    slug: "ocr-pdf",
    title: "OCR PDF",
    category: "PDF",
    group: "Edit PDF",
    icon: "doc",
    mode: "server",
    input: "PDF",
    output: "OCR text",
    accept: "application/pdf",
    action: "ocr-pdf",
    description: "Extract readable text from scanned PDF pages when OCR support is available.",
    useCase: "Helpful for scanned documents where normal copy and search does not work.",
  },
  {
    slug: "unlock-pdf",
    title: "Unlock PDF",
    category: "PDF",
    group: "PDF Security",
    icon: "unlock",
    mode: "server",
    input: "PDF",
    output: "Unlocked PDF",
    accept: "application/pdf",
    action: "unlock-pdf",
    option: "password",
    description: "Remove PDF password protection when you know the password.",
    useCase: "Use it only for documents you own or have permission to process.",
  },
  {
    slug: "translate-pdf",
    title: "Translate PDF",
    category: "PDF",
    group: "Convert from PDF",
    icon: "doc",
    mode: "server",
    input: "PDF",
    output: "Extracted text for translation",
    accept: "application/pdf",
    action: "translate-pdf",
    option: "language",
    description: "Extract PDF text into a clean translation-ready file.",
    useCase: "Useful when you need to copy PDF content into a translation workflow while preserving page references.",
  },
  {
    slug: "compare-pdf",
    title: "Compare PDF",
    category: "PDF",
    group: "Optimize PDF",
    icon: "organize",
    mode: "server",
    input: "PDF",
    output: "Comparison report",
    accept: "application/pdf",
    action: "compare-pdf",
    description: "Compare two PDF files and download a simple text report of page and text differences.",
    useCase: "Helpful when checking contract revisions, updated forms, draft reports, or before-and-after document versions.",
  },
  {
    slug: "protect-pdf",
    title: "Protect PDF",
    category: "PDF",
    group: "PDF Security",
    icon: "lock",
    mode: "server",
    input: "PDF",
    output: "Protected PDF",
    accept: "application/pdf",
    action: "protect-pdf",
    option: "password",
    description: "Add password protection to a PDF file.",
    useCase: "Useful for sensitive drafts, internal documents, and files that should not open without a password.",
  },
];

for (const tool of imageTools) {
  tool.faq = tool.mode === "server" ? sharedServerImageFaq : sharedImageFaq;
}

for (const tool of pdfTools) {
  tool.faq = sharedPdfFaq;
}

export const blogPosts = [
  {
    slug: "reduce-pdf-size-without-losing-quality",
    title: "5 Ways to Reduce PDF Size Without Losing Quality",
    description: "A practical guide to making PDF files smaller for email, uploads, and online forms while keeping documents readable.",
    category: "PDF Optimization",
    date: "2026-05-28",
    relatedTools: ["compress-pdf", "pdf-to-jpg", "merge-pdf", "split-pdf"],
    sections: [
      {
        heading: "Why PDF files become too large",
        body: [
          "PDF files often become large because they contain high-resolution images, scanned pages, embedded fonts, layers, annotations, or unnecessary metadata. A short document can still become difficult to email if every page contains a full-size scan.",
          "The best compression approach depends on the file. A text-heavy contract needs different treatment from a scanned brochure, a portfolio, or a report exported from presentation software.",
        ],
      },
      {
        heading: "Start with compression, then remove what you do not need",
        body: [
          "Use a PDF compression tool first, then review the output to make sure text is still crisp and images are acceptable. If the document contains pages you do not need, split the file or remove unused pages before sending it.",
          "When a PDF is only needed for preview, converting selected pages to JPG can also reduce sharing friction. Keep the original PDF if the document needs to preserve selectable text, page order, or official formatting.",
        ],
      },
      {
        heading: "Quality checks before sharing",
        body: [
          "Open the compressed PDF, zoom in on small text, check signature blocks, and confirm that images are still clear enough for the recipient. A file that uploads successfully but is unreadable will create more work later.",
          "For forms, portals, and legal documents, keep a copy of the original file and only share the compressed version after you have checked every important page.",
        ],
      },
    ],
  },
  {
    slug: "jpg-png-webp-which-format-to-use",
    title: "JPG vs PNG vs WebP: Which Image Format Should You Use?",
    description: "Learn when to use JPG, PNG, or WebP for websites, forms, screenshots, photos, and everyday file sharing.",
    category: "Image Formats",
    date: "2026-05-28",
    relatedTools: ["png-to-jpg", "jpg-to-png", "jpg-to-webp", "webp-to-jpg"],
    sections: [
      {
        heading: "Choose the format based on the job",
        body: [
          "JPG is usually best for photos because it creates smaller files and is accepted almost everywhere. PNG is better for screenshots, graphics, logos, and images that need transparency. WebP is useful for websites because it can keep good quality at a smaller size.",
          "The wrong format can make files unnecessarily large or cause upload problems. That is why simple conversion tools remain useful even when image apps are already installed.",
        ],
      },
      {
        heading: "Transparency and compatibility",
        body: [
          "JPG does not support transparency, so transparent areas need a background color. PNG and WebP can preserve transparency, which matters for logos, cutouts, icons, and design assets.",
          "Some older upload forms still reject WebP or AVIF. In that case, converting to JPG or PNG is often the fastest way to finish the task without changing the original image.",
        ],
      },
      {
        heading: "A simple rule of thumb",
        body: [
          "Use JPG for photos, PNG for screenshots or transparent graphics, and WebP for website assets when the platform supports it. Keep an original copy when quality matters, then export a smaller version for upload or delivery.",
        ],
      },
    ],
  },
  {
    slug: "safe-online-file-conversion-privacy-checklist",
    title: "A Privacy Checklist Before Using Any Online File Converter",
    description: "Use this checklist to decide when online conversion is safe, when browser-side tools are better, and when not to upload a file at all.",
    category: "Data Privacy",
    date: "2026-05-28",
    relatedTools: ["protect-pdf", "unlock-pdf", "compress-image", "image-to-pdf"],
    sections: [
      {
        heading: "Know what is inside the file",
        body: [
          "Before uploading anything, check whether the file includes financial details, medical information, private IDs, signatures, client data, or internal business records. If the content is sensitive, use a local workflow or a service approved by your organization.",
          "For ordinary files like product photos, public brochures, scanned homework, and basic document cleanup, online tools can be convenient as long as the service explains how files are handled.",
        ],
      },
      {
        heading: "Prefer browser-side conversion when possible",
        body: [
          "Some image conversions can run directly in the browser, which means the file does not need to be uploaded to a server. Browser-side tools are especially useful for common tasks like PNG to JPG, JPG to WebP, resizing images, and simple image-to-PDF jobs.",
          "More complex PDF and Office conversions usually need server processing. In those cases, check file limits, deletion windows, and whether the site makes the download step clear.",
        ],
      },
      {
        heading: "Review the result and remove extras",
        body: [
          "After conversion, open the result and check that it contains only the pages or images you intended to share. If needed, remove pages, add password protection, or create a separate copy for external sharing.",
        ],
      },
    ],
  },
  {
    slug: "convert-iphone-heic-photos-to-jpg",
    title: "How to Convert iPhone HEIC Photos to JPG for Upload Forms",
    description: "Why iPhones save HEIC photos, why some websites reject them, and how to make a JPG copy for forms and email.",
    category: "Image Formats",
    date: "2026-05-28",
    relatedTools: ["heic-to-jpg", "jpg-to-png", "compress-image", "image-to-pdf"],
    sections: [
      {
        heading: "Why HEIC causes upload problems",
        body: [
          "Many iPhones save photos as HEIC because the format keeps good image quality with smaller file sizes. The problem is compatibility: some websites, government portals, real estate systems, and older desktop apps still expect JPG.",
          "When a form rejects an iPhone photo, converting HEIC to JPG is usually faster than changing phone settings or retaking the image.",
        ],
      },
      {
        heading: "When JPG is the safer choice",
        body: [
          "JPG is widely accepted by email systems, upload forms, photo viewers, and document workflows. It is not always the smallest or newest format, but it is the practical default when compatibility matters more than advanced features.",
          "After conversion, check that the photo is upright, clear, and not too large for the upload limit. If necessary, compress or resize the JPG before submitting it.",
        ],
      },
      {
        heading: "Keep the original photo",
        body: [
          "A converted JPG copy is useful for sharing, but the original HEIC may still have better quality or metadata. Keep the original in your photo library and use the JPG copy for the website or document upload.",
        ],
      },
    ],
  },
  {
    slug: "organize-pdf-pages-before-sending",
    title: "How to Organize PDF Pages Before Sending a Document",
    description: "A simple workflow for merging, splitting, rotating, removing, and reordering PDF pages before sharing.",
    category: "Office Productivity",
    date: "2026-05-28",
    relatedTools: ["merge-pdf", "split-pdf", "remove-pdf-pages", "rotate-pdf"],
    sections: [
      {
        heading: "Start with the final reader",
        body: [
          "Before sending a PDF, think about what the recipient needs to do with it. A bank, client, school, or government portal may need one complete file, while a colleague may only need selected pages.",
          "Good PDF organization reduces back-and-forth. Put pages in a logical order, remove blanks, rotate sideways scans, and combine related files into one document when that makes the review easier.",
        ],
      },
      {
        heading: "Use the right tool for each cleanup step",
        body: [
          "Merge PDF combines files. Split PDF extracts a useful range. Remove PDF Pages deletes pages that should not be shared. Rotate PDF fixes sideways scans. Organize PDF lets you reorder pages when a scanned document is out of sequence.",
          "Always open the final PDF before sending it. Check page count, page order, orientation, and whether any private pages were accidentally included.",
        ],
      },
      {
        heading: "Create a clean sharing copy",
        body: [
          "Keep your working files separate from the final PDF. A clean sharing copy makes it easier to prove what was sent and avoids exposing notes, drafts, duplicate pages, or old attachments.",
        ],
      },
    ],
  },
  {
    slug: "word-excel-powerpoint-to-pdf-workflow",
    title: "When to Convert Word, Excel, or PowerPoint Files to PDF",
    description: "Use PDF copies to preserve layout, simplify sharing, and prevent accidental edits to office documents.",
    category: "Office Productivity",
    date: "2026-05-28",
    relatedTools: ["word-to-pdf", "excel-to-pdf", "powerpoint-to-pdf", "compress-pdf"],
    sections: [
      {
        heading: "PDF is best for final sharing",
        body: [
          "Word, Excel, and PowerPoint files are designed for editing. PDF is better when you want the recipient to view, print, upload, or archive a stable version of the document.",
          "Converting to PDF can preserve fonts, page breaks, slide layouts, headers, and footers more reliably than sending the original office file to someone using a different device or app.",
        ],
      },
      {
        heading: "Use office files for collaboration, PDF for delivery",
        body: [
          "Keep the original DOCX, XLSX, or PPTX while people are still editing. Once the document is final, create a PDF copy for submission, client review, signatures, or long-term records.",
          "For spreadsheets, check print areas and page breaks before converting. For presentations, review slide size and speaker notes so only the intended content appears in the PDF.",
        ],
      },
      {
        heading: "Compress the PDF if needed",
        body: [
          "Office exports can become large when they include high-resolution images or charts. If a portal or email system rejects the PDF, compress it and review the result before sending.",
        ],
      },
    ],
  },
];

export const legalPages = [
  {
    slug: "privacy",
    title: "Privacy Policy",
    description: "How FileForma handles uploaded files, browser conversions, analytics, and advertising.",
    body: [
      "Browser-based tools process files locally on your device and do not upload them to our servers.",
      "Server-based PDF tools temporarily process files only to complete the requested conversion. Temporary files are scheduled for deletion after 30 minutes.",
      "We may use Google Analytics to understand aggregate site usage, popular tools, page performance, and traffic sources. Analytics data helps us improve FileForma, and advertising placements must not interfere with uploads, conversion actions, or downloads.",
    ],
  },
  {
    slug: "terms",
    title: "Terms of Use",
    description: "The rules for using FileForma's free file conversion tools.",
    body: [
      "Use the service only for files you have the right to process.",
      "Do not upload malware, illegal content, or files intended to abuse the service.",
      "Conversions are provided as best-effort results. Always review important documents before sharing them.",
    ],
  },
  {
    slug: "contact",
    title: "Contact",
    description: "Contact FileForma for support, feedback, and policy questions.",
    body: [
      "For support, include the tool name, browser, file type, and the error message you saw.",
      "For privacy or advertising questions, include the page URL and a clear description of the issue.",
    ],
  },
  {
    slug: "about",
    title: "About FileForma",
    description: "FileForma is a practical file conversion site focused on images and PDFs.",
    body: [
      "FileForma focuses on the most common image and PDF tasks people need every day.",
      "The product favors fast browser-side conversion where possible and low-cost server processing only where it is necessary.",
    ],
  },
];
